### ISSUE TITLE
Errors with Xcode 8

### ISSUE THREAD

**Issue by changey** [taskrabbit/ReactNativeSampleApp#34]
Thanks for this great sample app! I was able to run it with Xcode 7, but when I switch to Xcode 8, I experienced the following errors. Has any one experienced similar issues? thx

```
2016-10-09 20:33:17.452 xcodebuild[31470:603747] Failed to locate a valid instance of CoreSimulatorService in the bootstrap.  Adding it now.
2016-10-09 20:33:17.461 xcodebuild[31470:603747] *** Assertion failure in -[SimServiceContext reloadServiceIfMovedOrAbortIfWeAreInvalid], /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreSimulator/CoreSimulator-209.19/CoreSimulator/SimServiceContext.m:536
** INTERNAL ERROR: Uncaught exception **
Uncaught Exception: The loaded com.apple.CoreSimulator.CoreSimulatorService job does not match our expectations: pathOfLoadedJob: /Applications/Xcode 8.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc/Contents/MacOS/com.apple.CoreSimulator.CoreSimulatorService, our frameworkPath: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework
Stack:
  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   +[NSException raise:format:arguments:] (in CoreFoundation)
  3   -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] (in Foundation)
  4   -[SimServiceContext reloadServiceIfMovedOrAbortIfWeAreInvalid] (in CoreSimulator)
  5   -[SimServiceContext connect] (in CoreSimulator)
  6   -[SimServiceContext initWithDeveloperDir:connectionType:] (in CoreSimulator)
  7   __63+[SimServiceContext sharedServiceContextForDeveloperDir:error:]_block_invoke_2 (in CoreSimulator)
  8   _dispatch_client_callout (in libdispatch.dylib)
  9   _dispatch_barrier_sync_f_invoke (in libdispatch.dylib)
 10   +[SimServiceContext sharedServiceContextForDeveloperDir:error:] (in CoreSimulator)
 11   __60+[SimServiceContext(DVTAdditions) dvt_sharedServiceContext:]_block_invoke (in DVTiPhoneSimulatorRemoteClient)
 12   _dispatch_client_callout (in libdispatch.dylib)
 13   dispatch_once_f (in libdispatch.dylib)
 14   +[SimServiceContext(DVTAdditions) dvt_sharedServiceContext:] (in DVTiPhoneSimulatorRemoteClient)
 15   __42-[DVTiPhoneSimulatorLocator startLocating]_block_invoke (in IDEiOSSupportCore)
 16   __DVTDispatchAsync_block_invoke (in DVTFoundation)
 17   _dispatch_call_block_and_release (in libdispatch.dylib)
 18   _dispatch_client_callout (in libdispatch.dylib)
 19   _dispatch_root_queue_drain (in libdispatch.dylib)
 20   _dispatch_worker_thread3 (in libdispatch.dylib)
 21   _pthread_wqthread (in libsystem_pthread.dylib)
 22   start_wqthread (in libsystem_pthread.dylib)

child_process.js:508
    throw err;
    ^

Error: Command failed: xcodebuild  GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS TEST_ENVIRONMENT=1' -workspace /Users/ericchang/Documents/work/ReactNativeSampleApp/ios/Sample.xcworkspace -scheme "Sample Test" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=latest' -configuration Debug OBJROOT=/Users/ericchang/Documents/work/ReactNativeSampleApp/testbuild/test_ios/build SYMROOT=/Users/ericchang/Documents/work/ReactNativeSampleApp/testbuild/test_ios/build ONLY_ACTIVE_ARCH=NO | xcpretty -c && exit ${PIPESTATUS[0]}
2016-10-09 20:33:17.194 xcodebuild[31470:603747] CoreSimulator is attempting to unload a stale CoreSimulatorService job.  Detected Xcode.app relocation or CoreSimulatorService version change.  Framework path (/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework) and version (209.19) does not match existing job path (/Applications/Xcode 8.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc/Contents/MacOS/com.apple.CoreSimulator.CoreSimulatorService) and version (303.8).
2016-10-09 20:33:17.452 xcodebuild[31470:603747] Failed to locate a valid instance of CoreSimulatorService in the bootstrap.  Adding it now.
2016-10-09 20:33:17.461 xcodebuild[31470:603747] *** Assertion failure in -[SimServiceContext reloadServiceIfMovedOrAbortIfWeAreInvalid], /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreSimulator/CoreSimulator-209.19/CoreSimulator/SimServiceContext.m:536
** INTERNAL ERROR: Uncaught exception **
Uncaught Exception: The loaded com.apple.CoreSimulator.CoreSimulatorService job does not match our expectations: pathOfLoadedJob: /Applications/Xcode 8.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc/Contents/MacOS/com.apple.CoreSimulator.CoreSimulatorService, our frameworkPath: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework
Stack:
  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   +[NSException raise:format:arguments:] (in CoreFoundation)
  3   -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] (in Foundation)
  4   -[SimServiceContext reloadServiceIfMovedOrAbortIfWeAreInvalid] (in CoreSimulator)
  5   -[SimServiceContext connect] (in CoreSimulator)
  6   -[SimServiceContext initWithDeveloperDir:connectionType:] (in CoreSimulator)
  7   __63+[SimServiceContext sharedServiceContextForDeveloperDir:error:]_block_invoke_2 (in CoreSimulator)
  8   _dispatch_client_callout (in libdispatch.dylib)
  9   _dispatch_barrier_sync_f_invoke (in libdispatch.dylib)
 10   +[SimServiceContext sharedServiceContextForDeveloperDir:error:] (in CoreSimulator)
 11   __60+[SimServiceContext(DVTAdditions) dvt_sharedServiceContext:]_block_invoke (in DVTiPhoneSimulatorRemoteClient)
 12   _dispatch_client_callout (in libdispatch.dylib)
 13   dispatch_once_f (in libdispatch.dylib)
 14   +[SimServiceContext(DVTAdditions) dvt_sharedServiceContext:] (in DVTiPhoneSimulatorRemoteClient)
 15   __42-[DVTiPhoneSimulatorLocator startLocating]_block_invoke (in IDEiOSSupportCore)
 16   __DVTDispatchAsync_block_invoke (in DVTFoundation)
 17   _dispatch_call_block_and_release (in libdispatch.dylib)
 18   _dispatch_client_callout (in libdispatch.dylib)
 19   _dispatch_root_queue_drain (in libdispatch.dylib)
 20   _dispatch_worker_thread3 (in libdispatch.dylib)
 21   _pthread_wqthread (in libsystem_pthread.dylib)
 22   start_wqthread (in libsystem_pthread.dylib)


    at checkExecSyncError (child_process.js:465:13)
    at Object.execSync (child_process.js:505:13)
    at Compiler.run (/Users/ericchang/Documents/work/ReactNativeSampleApp/tasks/compiler.js:21:27)
    at Compiler.buildIos (/Users/ericchang/Documents/work/ReactNativeSampleApp/tasks/compiler.js:103:8)
    at Compiler.build (/Users/ericchang/Documents/work/ReactNativeSampleApp/tasks/compiler.js:112:8)
    at Object.<anonymous> (/Users/ericchang/Documents/work/ReactNativeSampleApp/tasks/compile.js:5:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by ghost** [comment]
Try run 
 sudo chmod 755 /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc
